server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 65423299
    url: jdbc:mysql://b85198980ba0c3:65423299@us-cdbr-east-05.cleardb.net/heroku_ec1dbd646442805?reconnect=true
    username: b85198980ba0c3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000